"""add is active field to job provider table

Revision ID: 1f22d282e4cf
Revises: 25ca1351777e
Create Date: 2025-10-11 15:39:56.291564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f22d282e4cf'
down_revision: Union[str, Sequence[str], None] = '25ca1351777e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_providers', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_providers', 'is_active')
    # ### end Alembic commands ###
