"""jobs table init

Revision ID: 25ca1351777e
Revises: 
Create Date: 2025-10-11 14:36:06.775587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25ca1351777e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_providers',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_providers_base_url'), 'job_providers', ['base_url'], unique=True)
    op.add_column('job_postings', sa.Column('job_provider_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'job_postings', 'job_providers', ['job_provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'job_provider_id')
    op.drop_index(op.f('ix_job_providers_base_url'), table_name='job_providers')
    op.drop_table('job_providers')
    # ### end Alembic commands ###
