"""add unique field to job_posting table

Revision ID: 692bf553161b
Revises: 918f07ce0cbe
Create Date: 2025-10-12 09:19:09.420678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '692bf553161b'
down_revision: Union[str, Sequence[str], None] = '918f07ce0cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_job_url'), table_name='job_postings')
    op.create_index(op.f('ix_job_postings_job_url'), 'job_postings', ['job_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_job_url'), table_name='job_postings')
    op.create_index(op.f('ix_job_postings_job_url'), 'job_postings', ['job_url'], unique=False)
    # ### end Alembic commands ###
