"""add age field to specification table

Revision ID: 918f07ce0cbe
Revises: 9959eeb3ac89
Create Date: 2025-10-11 22:33:33.691507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '918f07ce0cbe'
down_revision: Union[str, Sequence[str], None] = '9959eeb3ac89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specifications', sa.Column('age', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specifications', 'age')
    # ### end Alembic commands ###
