"""add major field to specifcation table

Revision ID: 9959eeb3ac89
Revises: f3e64f9e8b62
Create Date: 2025-10-11 18:11:31.133631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9959eeb3ac89'
down_revision: Union[str, Sequence[str], None] = 'f3e64f9e8b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specifications', sa.Column('major', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specifications', 'major')
    # ### end Alembic commands ###
