"""add is_available_field

Revision ID: c6e3467f2d99
Revises: 898a8d368f68
Create Date: 2025-10-10 10:43:57.398918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6e3467f2d99'
down_revision: Union[str, Sequence[str], None] = '898a8d368f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openkerja', sa.Column('is_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('openkerja', 'is_available')
    # ### end Alembic commands ###
