"""init

Revision ID: e5767734d5db
Revises: 692bf553161b
Create Date: 2025-10-14 17:49:20.945467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5767734d5db'
down_revision: Union[str, Sequence[str], None] = '692bf553161b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_providers',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_syncing', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_providers_base_url'), 'job_providers', ['base_url'], unique=True)
    op.create_table('job_postings',
    sa.Column('job_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_modified', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number_of_vacancies', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_provider_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_provider_id'], ['job_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_job_url'), 'job_postings', ['job_url'], unique=True)
    op.create_table('positions',
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('application_contact_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('application_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('application_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_posting_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specifications',
    sa.Column('application_deadline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('education_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('experience_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_published', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_arrangement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_posting_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specifications')
    op.drop_table('positions')
    op.drop_index(op.f('ix_job_postings_job_url'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_job_providers_base_url'), table_name='job_providers')
    op.drop_table('job_providers')
    # ### end Alembic commands ###
