"""add syncinc field to provider table

Revision ID: f3e64f9e8b62
Revises: 1f22d282e4cf
Create Date: 2025-10-11 17:00:48.533501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3e64f9e8b62'
down_revision: Union[str, Sequence[str], None] = '1f22d282e4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_providers', sa.Column('is_syncing', sa.Boolean(), nullable=False))
    op.add_column('job_providers', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_providers', 'last_synced_at')
    op.drop_column('job_providers', 'is_syncing')
    # ### end Alembic commands ###
