import type {Metadata} from "next";
import {Geist} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import {BriefcaseIcon} from "lucide-react";
import {Badge} from "@/components/ui/badge";
import Container from "@/components/container";
import Link from "next/link";
import {NuqsAdapter} from "nuqs/adapters/next";
import QueryClientProvider from "@/providers/query-client-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Job Scout",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={cn("min-h-screen bg-background antialiased", geistSans.className)}
        >

        <NuqsAdapter>
            <QueryClientProvider>
                <header className="border-b h-14 flex items-center">
                    <Container className="w-full">
                        <div className="flex items-center gap-6">
                            <Link href="/">
                                <div className="flex items-center gap-2 group hover:cursor-pointer">
                                    <div className="size-7 bg-blue-700 flex items-center justify-center rounded-sm">
                                        <BriefcaseIcon size={16} strokeWidth={2} className="stroke-background"/>
                                    </div>
                                    <span
                                        className="font-semibold text-lg tracking-tight group-hover:text-blue-800">JobScout</span>
                                </div>
                            </Link>
                            <Badge variant="secondary" className="text-sm bg-zinc-200 rounded-sm h-8">Jobs</Badge>
                        </div>
                    </Container>
                </header>
                <main className="mb-7">
                    <Container>
                        {children}
                    </Container>
                </main>
            </QueryClientProvider>
        </NuqsAdapter>

        </body>
        </html>
    );
}
